unclassified:
  casCGlobalConfig:
    configurationPath: "configuration-as-code.yaml"
  gitLabServers:
    servers:
    - credentialsId: "Gitlab-zAuroraBuild_GL-access-token"
      manageWebHooks: true
      name: "Haufe Gitlab"
      # secretToken: "abc123"
      serverUrl: "https://gitlab.haufedev.systems"
