apiVersion: v1
kind: ConfigMap
metadata:
  name: jcasc-jobs
  namespace: dev-tools
data:
  casc-jobs.yaml: |
    jobs:
      - script: >
          organizationFolder('Bitstrum') {
              description('All Bitstrum repositories from BitBucket')
              displayName('Bitstrum Projects')
              organizations {
                  bitbucket {
                      repoOwner('Bitstrum')
                      credentialsId('bitbucket-user')
                      autoRegisterHooks(true)
                      traits {
                          sourceRegexFilter {
                              // A Java regular expression to restrict the project names.
                              regex('.*')
                          }
                      }
                  }
              }

              // "Project Recognizers"
              projectFactories {
                  workflowMultiBranchProjectFactory {
                      scriptPath 'Jenkinsfile'
                  }
              }

              // "Orphaned Item Strategy"
              orphanedItemStrategy {
                  discardOldItems {
                      daysToKeep(-1)
                      numToKeep(10)
                  }
              }

              // discover Branches (workaround due to JENKINS-46202)
              configure {
                  node ->
                      // node represents <jenkins.branch.OrganizationFolder>
                      def traits = node / 'navigators' / 'com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator' / 'traits'
                  traits << 'com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait' {
                      strategyId(3) // detect all branches
                  }
              }
          }
