---
apiVersion: "v1"
kind: "Pod"
metadata:
  annotations:
    buildUrl: "https://************/job/**********/job/master/7/"
    runUrl: "job/**********/job/master/7/"
  labels:
    jenkins: "agent"
    jenkins/label-digest: "81fd8c28e52119b084c57113ef6c0a551852466b"
    jenkins/label: "********-4fdec17f-5c39-47f0-821e-b3619a448ea1"
  name: "********-4fdec17f-5c39-47f0-821e-b3619a448ea1-6ppq8-62t70"
spec:
  containers:
  - command:
    - "cat"
    image: "amazon/aws-cli"
    name: "aws"
    tty: true
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - command:
    - "cat"
    image: "docker:stable-git"
    name: "docker"
    tty: true
    volumeMounts:
    - mountPath: "/var/run/docker.sock"
      name: "docker-socket"
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - env:
    - name: "JENKINS_SECRET"
      value: "********"
    - name: "JENKINS_AGENT_NAME"
      value: "********-4fdec17f-5c39-47f0-821e-b3619a448ea1-6ppq8-62t70"
    - name: "JENKINS_NAME"
      value: "********-4fdec17f-5c39-47f0-821e-b3619a448ea1-6ppq8-62t70"
    - name: "JENKINS_AGENT_WORKDIR"
      value: "/home/jenkins/agent"
    - name: "JENKINS_URL"
      value: "https://************/"
    image: "jenkins/inbound-agent:4.3-4"
    name: "jnlp"
    resources:
      limits: {}
      requests:
        memory: "256Mi"
        cpu: "100m"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  nodeSelector:
    kubernetes.io/os: "linux"
  restartPolicy: "Never"
  securityContext:
    fsGroup: 0
    runAsUser: 0
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"
  - hostPath:
      path: "/var/run/docker.sock"
    name: "docker-socket"